{{- with .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-mysqldb-secret
type: {{ .type }}
data:
  {{- with .data }}
  DB_PASSWORD: {{ .DB_PASSWORD }}  # base64 for "root" & configured for webapp deployment env
  MYSQL_ROOT_PASSWORD: {{ .MYSQL_ROOT_PASSWORD }}   # base64 for "root" & configured for mysqldb statefulset env
  {{- end }}
{{- end }}
