{{- with index .Values "mysqldb-pvc" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-mysqldb-pv
spec:
  capacity:
    storage: {{ .storage }}
  volumeMode: {{ .volumeMode }}
  storageClassName:  {{ $.Release.Name }}-mysqldb-sc
  accessModes:
  {{- range .accessModes }}
    - {{ . }}
  {{- end }}
  {{- with .hostPath }}
  hostPath:
    path: {{ .path }}
    type: {{ .type }}
  {{- end }}
{{- end }}
